### ISSUE TITLE
Allow floating point values in config

### ISSUE THREAD

**Issue by threddast** [zer0-x/ianny#1]
Hi, thank you for making this project!

I would like to have my short breaks be 30 seconds long. This should be possible by setting the break value to 0.5 but currently it returns an error.

**Comment by zefr0x** [comment]
You are welcome,

This was intentional behavior, since in the worst case it will check for a break every minute. If I used seconds as a unit it might check every single second for a break and this will use more CPU of course.

Any way it's not a huge process, I was just very careful of making it as quiet as possible, but it's a very simple thing and it's okay to not do it. I thought a longer break was always a good thing. 

I will change the time unit or I might just add another option to select a unit for compatibility. It should happen in the next release.

Thanks for the feedback ☺
