### ISSUE TITLE
Standby in the locked screen/off screen

### ISSUE THREAD

**Issue by vanarok** [zer0-x/ianny#9]
Thank you for this great utility, it has become a permanent fixture in my arsenal for heel pain :)

I have one problem that bothers me, it is that I can not close the lid of the laptop and go for a walk, because when I return to work, the progress of rest is still in progress. 

I see two solutions:

1. Track lid/locked screen system events (I think this would be very complicated) 
2. Add a command to stop and resume ianny so that it can be attached in the system to the lid/locked screen event.

**Comment by zefr0x** [comment]
You are welcome, I appreciate that it helped you 😄

The issue is that when you close the lid of the laptop it will be suspend (sleep) so the timer will not make any progress.

We should be able to catch systemd's loginctl `before-sleep` event via DBus.
But I prefer that we just relay on the system clock for the timer, so we keep track of time if the user came back before the break ends or before the idle_timeout reached.

It shouldn't be complicated, just simple modification in the timer implementation.
